export type LabCaseStatus =
  | 'Aguardando Análise Técnica'
  | 'Em Análise Técnica'
  | 'Planejamento Elaborado'
  | 'Planejamento Entregue'

export type MWSProtocol = 'Classe I' | 'Classe II' | 'Classe III' | 'Classe IV' | 'Classe V'

export type RoboticProductionStage =
  | 'dobagem_modelagem'
  | 'acabamento'
  | 'controle_qualidade'
  | 'pronto_expedicao'

export interface LabClinicalCase {
  id: string // Formato: CAS-2026-XXX-MWS
  patientName: string
  patientAge: number
  dentistId: string
  dentistName: string
  dentistCity: string
  dentistCro: string
  protocol: MWSProtocol
  status: LabCaseStatus
  submissionDate: string
  slaDeadline: string
  slaHoursLeft: number // negativo = atrasado
  slaStatus: 'normal' | 'alerta' | 'estourado'
  technicianAssigned: string
  mentorAssigned: string // A partir da entrega do planejamento, vira o mentor do caso
  // Observações Clínicas & Queixa Principal (enviada pelo ortodontista)
  clinicalObservations: string
  chiefComplaint: string
  // Campos técnicos MWS
  upperArchDetails: string
  lowerArchDetails: string
  wireType: string
  wireGauges: string // Calibres NiTi Copper, TMA, etc.
  stopsAndAttachments: string
  // Notas editáveis no Lab
  technicianNotes: string // "Nota do Técnico Lab" (planejamento elaborado e orientações de execução)
  mentorClinicalNotes: string // "Nota Clínica do seu Mentor" (informações complementares do mentor)
  // Retorno do ortodontista (após Planejamento Entregue)
  dentistFeedbackStatus?: 'pendente' | 'aprovado' | 'ajustes_solicitados'
  dentistFeedbackNotes?: string
  feedbackDate?: string
  // Produção Robótica
  productionStage?: RoboticProductionStage
  productionBatchId?: string
  roboticCellId?: string
}

export interface LabTeamMember {
  id: string
  name: string
  role:
    | 'Técnico Especialista'
    | 'Técnica Especialista'
    | 'Planejador & Mentor'
    | 'Coordenador Técnico'
    | 'Especialista em Robótica'
  avatarSeed: number
  email: string
  casesAssignedCount: number
  capacity: number
  specialty: string
  status: 'ativo' | 'em_capacitacao' | 'ferias'
  completedThisMonth: number
  npsScore: number
}

export interface RoboticProductionOrder {
  id: string
  caseId: string
  patientName: string
  dentistName: string
  dentistCity: string
  protocol: MWSProtocol
  wireType: string
  upperWireGauge: string
  lowerWireGauge: string
  stage: RoboticProductionStage
  priority: 'alta' | 'normal' | 'urgente'
  roboticCell: string // ex: Célula Robótica KUKA-MW-01
  startedAt: string
  estimatedCompletion: string
  qualityCheckPassed: boolean
  technicianInCharge: string
}

export interface LabSlaMetric {
  stage: LabCaseStatus
  averageTimeHours: number
  targetHours: number
  onTimePercentage: number
  delayedCasesCount: number
}

// 54 Casos Totais:
// 12 Aguardando Análise Técnica
// 18 Em Análise Técnica
// 14 Planejamento Elaborado
// 10 Planejamento Entregue
export const MOCK_LAB_CASES: LabClinicalCase[] = [
  // 12 Aguardando Análise Técnica
  {
    id: 'CAS-2026-001-MWS',
    patientName: 'Carla Souza',
    patientAge: 29,
    dentistId: 'DENT-007',
    dentistName: 'Dra. Fernanda Albuquerque',
    dentistCity: 'Porto Alegre - RS',
    dentistCro: 'CRO-RS 19821',
    protocol: 'Classe V',
    status: 'Aguardando Análise Técnica',
    submissionDate: '24/02/2026',
    slaDeadline: '26/02/2026',
    slaHoursLeft: -6,
    slaStatus: 'estourado',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations:
      'Mordida cruzada unilateral e assimetria severa em paciente adulto. Solicita avaliação para aparelho lingual com ancoragem esquelética.',
    chiefComplaint: 'Assimetria ao sorrir e dificuldade mastigatória do lado esquerdo.',
    upperArchDetails:
      'Contração do arco posterior superior direito; apinhamento moderado anterior.',
    lowerArchDetails: 'Desvio de linha média inferior de 3.5mm para a direita.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Arcada Superior: 0.014 CuNiTi / Arcada Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops linguais entre caninos e pré-molares; botões linguais no 16 e 26.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-002-MWS',
    patientName: 'Eduardo Martins',
    patientAge: 34,
    dentistId: 'DENT-002',
    dentistName: 'Dr. Roberto Takahashi',
    dentistCity: 'São Paulo - SP',
    dentistCro: 'CRO-SP 44102',
    protocol: 'Classe I',
    status: 'Aguardando Análise Técnica',
    submissionDate: '25/02/2026',
    slaDeadline: '27/02/2026',
    slaHoursLeft: 4,
    slaStatus: 'alerta',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations:
      'Diastema interincisal superior de 2.2mm com rotação dos laterais. Excelente higiene bucal.',
    chiefComplaint: 'Espaço entre os dentes da frente e sorriso desalinhado.',
    upperArchDetails: 'Diastema 11-21; giroversão de 12 e 22.',
    lowerArchDetails: 'Alinhamento regular; leve apinhamento anteroinferior.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Arcada Superior: 0.014 CuNiTi / Arcada Inferior: 0.012 CuNiTi',
    stopsAndAttachments:
      'Sem necessidade de dobras compensatórias severas; stops nos primeiros molares.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-003-MWS',
    patientName: 'Beatriz Vasconcelos',
    patientAge: 22,
    dentistId: 'DENT-004',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    dentistCro: 'CRO-MG 31209',
    protocol: 'Classe II',
    status: 'Aguardando Análise Técnica',
    submissionDate: '25/02/2026',
    slaDeadline: '28/02/2026',
    slaHoursLeft: 18,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations:
      'Sobressaliência de 5mm com sobremordida de 60%. Perfil convexo com bom vedamento labial.',
    chiefComplaint: 'Dentes superiores projetados para a frente.',
    upperArchDetails: 'Protrusão dos incisivos centrais; curva de Spee acentuada.',
    lowerArchDetails: 'Apinhamento ântero-inferior moderado.',
    wireType: 'Fio Mágico Copper NiTi + TMA Lingual Customizado',
    wireGauges: 'Superior: 0.016x0.022 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops mesiais nos molares linguais.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-004-MWS',
    patientName: 'Gabriel Sampaio',
    patientAge: 41,
    dentistId: 'DENT-005',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    dentistCro: 'CRO-PR 28410',
    protocol: 'Classe III',
    status: 'Aguardando Análise Técnica',
    submissionDate: '25/02/2026',
    slaDeadline: '28/02/2026',
    slaHoursLeft: 22,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations:
      'Mecânica compensatória em Classe III cirúrgico-recusada pelo paciente. Procura discrição total.',
    chiefComplaint: 'Mordida de topo e incisivos inferiores visíveis à frente dos superiores.',
    upperArchDetails: 'Proclinação planejada dos incisivos superiores com torque lingual.',
    lowerArchDetails: 'Verticalização e retroinclinação dos incisivos inferiores.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.016x0.022 TMA Lingual',
    stopsAndAttachments: 'Botões linguais para elásticos intermaxilares leves.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-005-MWS',
    patientName: 'Camila Nogueira',
    patientAge: 27,
    dentistId: 'DENT-006',
    dentistName: 'Dr. Gustavo Siqueira',
    dentistCity: 'Campinas - SP',
    dentistCro: 'CRO-SP 52914',
    protocol: 'Classe I',
    status: 'Aguardando Análise Técnica',
    submissionDate: '26/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 36,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations: 'Apinhamento ântero-superior com caninos ectópicos em posição alta.',
    chiefComplaint: 'Caninos pontudos e saltados para fora.',
    upperArchDetails: 'Caninos vestibularizados (13 e 23); falta de espaço de 3mm no arco.',
    lowerArchDetails: 'Alinhamento estável.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: Sem intervenção inicial',
    stopsAndAttachments: 'Tubos e braquetes linguais de perfil ultra-baixo.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-006-MWS',
    patientName: 'Thiago Faria',
    patientAge: 31,
    dentistId: 'DENT-008',
    dentistName: 'Dr. Bruno Silveira',
    dentistCity: 'Ribeirão Preto - SP',
    dentistCro: 'CRO-SP 38921',
    protocol: 'Classe IV',
    status: 'Aguardando Análise Técnica',
    submissionDate: '26/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 40,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations:
      'Mordida aberta anterior de 3mm em paciente com hábito prévio de deglutição atípica.',
    chiefComplaint: 'Não consigo cortar os alimentos com os dentes da frente.',
    upperArchDetails: 'Interposição lingual; extrusão e nivelamento anterior.',
    lowerArchDetails: 'Curva de Spee reversa.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.016 CuNiTi',
    stopsAndAttachments: 'Levantes de mordida posteriores em resina nos molares inferiores.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-007-MWS',
    patientName: 'Leticia Ramos',
    patientAge: 38,
    dentistId: 'DENT-002',
    dentistName: 'Dr. Roberto Takahashi',
    dentistCity: 'São Paulo - SP',
    dentistCro: 'CRO-SP 44102',
    protocol: 'Classe II',
    status: 'Aguardando Análise Técnica',
    submissionDate: '26/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 42,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations:
      'Recidiva ortodôntica pós-tratamento convencional da adolescência. Requer aparelho invisível.',
    chiefComplaint: 'Dentes entortaram novamente e não quero usar aparelho visível na frente.',
    upperArchDetails: 'Giroversões 12 e 21; relação molar de 1/2 cúspide de Classe II.',
    lowerArchDetails: 'Contrição intercaninos.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Pequenos stops linguais para estabilização do fio.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-008-MWS',
    patientName: 'Marcos Vinicius Paiva',
    patientAge: 45,
    dentistId: 'DENT-009',
    dentistName: 'Dra. Renata Fontes',
    dentistCity: 'Rio de Janeiro - RJ',
    dentistCro: 'CRO-RJ 22419',
    protocol: 'Classe I',
    status: 'Aguardando Análise Técnica',
    submissionDate: '26/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 48,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations:
      'Planejamento pré-protético com verticalização de molar 47 e fechamento de espaços.',
    chiefComplaint: 'Preparar a boca para implantes nos dentes posteriores.',
    upperArchDetails: 'Arco bem delineado sem intervenção imediata.',
    lowerArchDetails: 'Molar inclinado para mesial com perda precoce do 46.',
    wireType: 'Fio Mágico TMA Lingual Customizado',
    wireGauges: 'Inferior: 0.016x0.022 TMA Lingual',
    stopsAndAttachments: 'Braço de força lingual para verticalização de molar.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-009-MWS',
    patientName: 'Juliana Pinho',
    patientAge: 26,
    dentistId: 'DENT-004',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    dentistCro: 'CRO-MG 31209',
    protocol: 'Classe II',
    status: 'Aguardando Análise Técnica',
    submissionDate: '26/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 52,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations:
      'Mordida profunda de 4.5mm com toque no palato. Exige desoclusão imediata.',
    chiefComplaint: 'Sinto os dentes de baixo machucando o céu da boca.',
    upperArchDetails: 'Incisivos palatinizados; necessidade de torque vestibular de coroa.',
    lowerArchDetails: 'Incisivos inferiores com altura reduzida.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi com curva reversa / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Platôs de mordida linguais nos incisivos superiores.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-010-MWS',
    patientName: 'Felipe Alcantara',
    patientAge: 33,
    dentistId: 'DENT-005',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    dentistCro: 'CRO-PR 28410',
    protocol: 'Classe III',
    status: 'Aguardando Análise Técnica',
    submissionDate: '27/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 60,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations: 'Tendência a Classe III esquelética moderada. Perfil reto.',
    chiefComplaint: 'Sorriso invertido e desgaste nos dentes anteriores.',
    upperArchDetails: 'Arco atrésico superior com necessidade de expansão robótica do fio.',
    lowerArchDetails: 'Desgaste incisal nos caninos e centrais inferiores.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi expandido / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops linguais bilaterais pré-molares.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-011-MWS',
    patientName: 'Patricia Guedes',
    patientAge: 30,
    dentistId: 'DENT-010',
    dentistName: 'Dr. Marcelo Mendonça',
    dentistCity: 'Brasília - DF',
    dentistCro: 'CRO-DF 14930',
    protocol: 'Classe I',
    status: 'Aguardando Análise Técnica',
    submissionDate: '27/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 64,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations: 'Leve apinhamento bidental. Foco em estética rápida e conforto na fala.',
    chiefComplaint: 'Pequenos dentes tortos que me incomodam em fotos.',
    upperArchDetails: 'Discrepância de modelo de apenas 2mm.',
    lowerArchDetails: 'Incisivo lateral discretamente lingualizado.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.012 CuNiTi / Inferior: 0.012 CuNiTi',
    stopsAndAttachments: 'Colagem indireta lingual de precisão sem stops volumosos.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },
  {
    id: 'CAS-2026-012-MWS',
    patientName: 'Rodrigo Brandão',
    patientAge: 39,
    dentistId: 'DENT-006',
    dentistName: 'Dr. Gustavo Siqueira',
    dentistCity: 'Campinas - SP',
    dentistCro: 'CRO-SP 52914',
    protocol: 'Classe V',
    status: 'Aguardando Análise Técnica',
    submissionDate: '27/02/2026',
    slaDeadline: '03/03/2026',
    slaHoursLeft: 72,
    slaStatus: 'normal',
    technicianAssigned: 'Não atribuído',
    mentorAssigned: 'Fila de Distribuição de Mentoria',
    clinicalObservations:
      'Mordida cruzada posterior bilateral em adulto com fissura palatina operada.',
    chiefComplaint: 'Mordida travada e dores na articulação.',
    upperArchDetails: 'Cicatriz palatina com colapso do arco superior.',
    lowerArchDetails: 'Arco bem formado, forma parabólica.',
    wireType: 'Fio Mágico TMA Lingual Robótico com Curvatura Customizada',
    wireGauges: 'Superior: 0.016x0.022 TMA Lingual / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Botões para elásticos cruzados vestibulares/palatinos.',
    technicianNotes: '',
    mentorClinicalNotes: '',
  },

  // 18 Em Análise Técnica
  {
    id: 'CAS-2026-013-MWS',
    patientName: 'Pedro Lima',
    patientAge: 25,
    dentistId: 'DENT-006',
    dentistName: 'Dr. Gustavo Siqueira',
    dentistCity: 'Campinas - SP',
    dentistCro: 'CRO-SP 52914',
    protocol: 'Classe IV',
    status: 'Em Análise Técnica',
    submissionDate: '22/02/2026',
    slaDeadline: '26/02/2026',
    slaHoursLeft: -12,
    slaStatus: 'estourado',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations:
      'Diagramação de torque e colagem indireta guiada por computador. Mordida cruzada anterior.',
    chiefComplaint: 'Dentes anteriores batendo de ponta e travando a mastigação.',
    upperArchDetails: 'Palatinização de 11 e 21; expansão leve nos setores posteriores.',
    lowerArchDetails: 'Vestibularização de caninos inferiores.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops no arco lingual nos dentes 15 e 25.',
    technicianNotes:
      'Análise de torque digital iniciada. Dobra de 3ª ordem calculada para incisivos centrais superiores.',
    mentorClinicalNotes:
      'Recomendo manter torque passivo nas primeiras 6 semanas antes de progredir para fio retangular.',
  },
  {
    id: 'CAS-2026-014-MWS',
    patientName: 'Mariana Azevedo',
    patientAge: 32,
    dentistId: 'DENT-004',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    dentistCro: 'CRO-MG 31209',
    protocol: 'Classe II',
    status: 'Em Análise Técnica',
    submissionDate: '23/02/2026',
    slaDeadline: '27/02/2026',
    slaHoursLeft: 2,
    slaStatus: 'alerta',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Classe II divisão 1 com protrusão maxilar acentuada. Análise tomográfica recebida e acoplada ao STL.',
    chiefComplaint: 'Gengiva aparente e dentes superiores para frente.',
    upperArchDetails: 'Intrusão anterior requerida com dobras de 2ª ordem robotizadas.',
    lowerArchDetails: 'Mecânica de nivelamento da curva de Spee.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops bilaterais e ganchos linguais para elásticos de Classe II.',
    technicianNotes:
      'Segmentação 3D das coroas clínicas finalizada. Modelagem do fio lingual em andamento no software CAD MWS.',
    mentorClinicalNotes:
      'Atenção aos pontos de contato oclusais com os braquetes linguais inferiores.',
  },
  {
    id: 'CAS-2026-015-MWS',
    patientName: 'André Carvalho',
    patientAge: 37,
    dentistId: 'DENT-002',
    dentistName: 'Dr. Roberto Takahashi',
    dentistCity: 'São Paulo - SP',
    dentistCro: 'CRO-SP 44102',
    protocol: 'Classe I',
    status: 'Em Análise Técnica',
    submissionDate: '23/02/2026',
    slaDeadline: '27/02/2026',
    slaHoursLeft: 6,
    slaStatus: 'alerta',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Apinhamento severo superior e inferior com biprotrusão leve. Preferência por não realizar exodontias.',
    chiefComplaint: 'Dentes apinhados e dificuldade no uso de fio dental.',
    upperArchDetails: 'Desgaste interproximal programado de 0.3mm por contato.',
    lowerArchDetails: 'Expansão lingual suave com fio pré-conformado por robótica.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops nos molares linguais.',
    technicianNotes:
      'Estudo do espaço presente versus requerido indica ganho de 2.8mm com IPR e desverticalização.',
    mentorClinicalNotes:
      'Protocolo validado clinicamente. Fio lingual 0.014 é a escolha ideal para o início suave.',
  },
  {
    id: 'CAS-2026-016-MWS',
    patientName: 'Tatiane Rios',
    patientAge: 28,
    dentistId: 'DENT-005',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    dentistCro: 'CRO-PR 28410',
    protocol: 'Classe III',
    status: 'Em Análise Técnica',
    submissionDate: '24/02/2026',
    slaDeadline: '28/02/2026',
    slaHoursLeft: 20,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Pseudo-Classe III com desvio funcional em máxima intercuspidação. Desprogramação articular recomendada.',
    chiefComplaint: 'Queixo projetado para frente ao fechar a boca.',
    upperArchDetails: 'Desbloqueio anterior com levante nos molares.',
    lowerArchDetails: 'Nivelamento e alinhamento lingual.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Levante oclusal e batentes linguais.',
    technicianNotes:
      'Verificando trajetória de arco e ausência de colisão dos braquetes linguais durante a oclusão cêntrica.',
    mentorClinicalNotes:
      'O ortodontista solicitou orientações para a colagem indireta guiada; incluir no relatório final.',
  },
  {
    id: 'CAS-2026-017-MWS',
    patientName: 'Guilherme Bastos',
    patientAge: 40,
    dentistId: 'DENT-007',
    dentistName: 'Dra. Fernanda Albuquerque',
    dentistCity: 'Porto Alegre - RS',
    dentistCro: 'CRO-RS 19821',
    protocol: 'Classe II',
    status: 'Em Análise Técnica',
    submissionDate: '24/02/2026',
    slaDeadline: '28/02/2026',
    slaHoursLeft: 24,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations:
      'Classe II subdivisão direita. Perda do primeiro pré-molar inferior esquerdo antiga.',
    chiefComplaint: 'Linha média torta e sorriso torto.',
    upperArchDetails: 'Ajuste de linha média superior com torque diferencial.',
    lowerArchDetails: 'Mesialização do bloco posterior inferior esquerdo.',
    wireType: 'Fio Mágico TMA Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.016x0.022 TMA Lingual',
    stopsAndAttachments: 'Stops no 37 e 47.',
    technicianNotes: 'Simulação de mecânica assimétrica em andamento no módulo CAD.',
    mentorClinicalNotes:
      'Aparelho lingual MWS com braços de força específicos para controle de rotação no dente 35.',
  },
  {
    id: 'CAS-2026-018-MWS',
    patientName: 'Renata Figueiredo',
    patientAge: 35,
    dentistId: 'DENT-008',
    dentistName: 'Dr. Bruno Silveira',
    dentistCity: 'Ribeirão Preto - SP',
    dentistCro: 'CRO-SP 38921',
    protocol: 'Classe I',
    status: 'Em Análise Técnica',
    submissionDate: '24/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 28,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Mordida aberta leve anterior decorrente de posicionamento lingual ao engolir.',
    chiefComplaint: 'Pequena fresta entre os dentes da frente.',
    upperArchDetails: 'Extrusão anterior e nivelamento do plano incisal.',
    lowerArchDetails: 'Alinhamento lingual sem sobreextrusão dos caninos.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops linguais anteriores.',
    technicianNotes:
      'Curva de conformação do fio superior desenhada com compensação lingual de 0.5mm.',
    mentorClinicalNotes: 'Orientar fonoaudiologia concomitante ao tratamento com o Fio Mágico.',
  },
  {
    id: 'CAS-2026-019-MWS',
    patientName: 'Felipe Fontana',
    patientAge: 23,
    dentistId: 'DENT-002',
    dentistName: 'Dr. Roberto Takahashi',
    dentistCity: 'São Paulo - SP',
    dentistCro: 'CRO-SP 44102',
    protocol: 'Classe V',
    status: 'Em Análise Técnica',
    submissionDate: '25/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 30,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Complexidade de ancoragem esquelética com mini-implantes associados aos fios linguais robóticos.',
    chiefComplaint: 'Dentes posteriores cruzados dos dois lados.',
    upperArchDetails: 'Expansão robótica diferencial com braço palatino soldado no fio.',
    lowerArchDetails: 'Estabilização passiva.',
    wireType: 'Fio Mágico TMA Lingual Robótico com Braços Customizados',
    wireGauges: 'Superior: 0.017x0.025 TMA Lingual / Inferior: 0.016 CuNiTi',
    stopsAndAttachments: 'Encaixes linguais para ancoragem esquelética.',
    technicianNotes: 'Estudo biomecânico detalhado em execução.',
    mentorClinicalNotes:
      'Caso elegível para apresentação na Comunidade MWS como exemplo de 3ª geração ortodôntica.',
  },
  {
    id: 'CAS-2026-020-MWS',
    patientName: 'Luciana Teles',
    patientAge: 39,
    dentistId: 'DENT-004',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    dentistCro: 'CRO-MG 31209',
    protocol: 'Classe II',
    status: 'Em Análise Técnica',
    submissionDate: '25/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 32,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations: 'Classe II esquelética com compensação dentária prévia inadequada.',
    chiefComplaint: 'Sensação de boca cheia e inclinação excessiva dos dentes da frente.',
    upperArchDetails: 'Retração em massa anterior com controle de torque.',
    lowerArchDetails: 'Intrusão relativa dos incisivos inferiores.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016x0.022 CuNiTi / Inferior: 0.016 CuNiTi',
    stopsAndAttachments: 'Stops mesiais e dobras de primeira ordem para rotações.',
    technicianNotes: 'Curvas de compensação prontas para validação do mentor.',
    mentorClinicalNotes: 'Revisando torque radicular palatino para evitar contato cortical.',
  },
  {
    id: 'CAS-2026-021-MWS',
    patientName: 'Gustavo Paes',
    patientAge: 31,
    dentistId: 'DENT-009',
    dentistName: 'Dra. Renata Fontes',
    dentistCity: 'Rio de Janeiro - RJ',
    dentistCro: 'CRO-RJ 22419',
    protocol: 'Classe I',
    status: 'Em Análise Técnica',
    submissionDate: '25/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 34,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Diastema generalizado superior decorrente de freio labial teto fibroso operado.',
    chiefComplaint: 'Espaços entre todos os dentes de cima.',
    upperArchDetails: 'Mesialização dos caninos e pré-molares linguais.',
    lowerArchDetails: 'Arco lingual estabilizado.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: Sem aparelho ativo',
    stopsAndAttachments: 'Stops de contenção nos molares.',
    technicianNotes: 'Planejamento de fechamento em massa com controle de inclinação lingual.',
    mentorClinicalNotes: 'Excelente prognóstico com o fio lingual MWS.',
  },
  {
    id: 'CAS-2026-022-MWS',
    patientName: 'Helena Miranda',
    patientAge: 44,
    dentistId: 'DENT-010',
    dentistName: 'Dr. Marcelo Mendonça',
    dentistCity: 'Brasília - DF',
    dentistCro: 'CRO-DF 14930',
    protocol: 'Classe III',
    status: 'Em Análise Técnica',
    submissionDate: '25/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 44,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Mordida cruzada anterior unilateral (dente 22 cruzado em relação ao 32 e 33).',
    chiefComplaint: 'Um dente de cima fica preso atrás do de baixo.',
    upperArchDetails: 'Desbloqueio com levante lingual e projeção controlada do 22.',
    lowerArchDetails: 'Lingualização suave do setor ântero-inferior.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops e levante em compósito lingual.',
    technicianNotes: 'Dobra de 1ª ordem robotizada adicionada na face lingual do 22.',
    mentorClinicalNotes:
      'Evitar força excessiva no 22 devido a histórico periodontal favorável porém delicado.',
  },
  {
    id: 'CAS-2026-023-MWS',
    patientName: 'Tiago Bernardes',
    patientAge: 29,
    dentistId: 'DENT-005',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    dentistCro: 'CRO-PR 28410',
    protocol: 'Classe I',
    status: 'Em Análise Técnica',
    submissionDate: '25/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 46,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Apinhamento ântero-inferior com apinhamento leve superior. Paciente exige tempo de tratamento curto.',
    chiefComplaint: 'Dentes de baixo tortos e incômodo estético.',
    upperArchDetails: 'Nivelamento e conformação parabólica do fio lingual.',
    lowerArchDetails: 'Desdobramento do apinhamento com IPR planejado de 0.2mm por ponto.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops mesiais dos primeiros molares.',
    technicianNotes: 'Diagrama de arcos individualizados gerado pelo algoritmo MWS.',
    mentorClinicalNotes: 'Caso clássico de indicação primária do Fio Mágico lingual.',
  },
  {
    id: 'CAS-2026-024-MWS',
    patientName: 'Priscila Prado',
    patientAge: 36,
    dentistId: 'DENT-006',
    dentistName: 'Dr. Gustavo Siqueira',
    dentistCity: 'Campinas - SP',
    dentistCro: 'CRO-SP 52914',
    protocol: 'Classe II',
    status: 'Em Análise Técnica',
    submissionDate: '26/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 50,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations:
      'Mordida profunda com desvio de linha média superior para esquerda de 1.8mm.',
    chiefComplaint: 'Sorriso torto e queixa de cansaço nos músculos da face.',
    upperArchDetails: 'Correção de linha média com vetor de força lingual.',
    lowerArchDetails: 'Nivelamento da curva de Spee profunda.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Levantes de mordida anteriores linguais.',
    technicianNotes: 'Modelagem dos levantes virtuais acoplados aos braquetes linguais.',
    mentorClinicalNotes: 'Orientar ortodontista quanto à adesão dos stops posteriores.',
  },
  {
    id: 'CAS-2026-025-MWS',
    patientName: 'Marcelo Cordeiro',
    patientAge: 47,
    dentistId: 'DENT-007',
    dentistName: 'Dra. Fernanda Albuquerque',
    dentistCity: 'Porto Alegre - RS',
    dentistCro: 'CRO-RS 19821',
    protocol: 'Classe IV',
    status: 'Em Análise Técnica',
    submissionDate: '26/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 54,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Mordida aberta bilateral posterior decorrente de hábito de sucção tardio.',
    chiefComplaint: 'Dentes do fundo não encostam ao mastigar.',
    upperArchDetails: 'Extrusão programada dos setores médios com torque compensatório.',
    lowerArchDetails: 'Nivelamento passivo lingual.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops linguais caninos.',
    technicianNotes: 'Simulação de contato oclusal tridimensional no software de mentoria.',
    mentorClinicalNotes: 'Planejamento em fase final de validação.',
  },
  {
    id: 'CAS-2026-026-MWS',
    patientName: 'Sabrina Toledo',
    patientAge: 26,
    dentistId: 'DENT-008',
    dentistName: 'Dr. Bruno Silveira',
    dentistCity: 'Ribeirão Preto - SP',
    dentistCro: 'CRO-SP 38921',
    protocol: 'Classe I',
    status: 'Em Análise Técnica',
    submissionDate: '26/02/2026',
    slaDeadline: '03/03/2026',
    slaHoursLeft: 58,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Apinhamento anterior com rotação de 45 graus no incisivo central superior esquerdo (21).',
    chiefComplaint: 'Dente da frente totalmente virado de lado.',
    upperArchDetails: 'Dobra de primeira ordem acentuada desenhada para desvirar o 21.',
    lowerArchDetails: 'Manutenção de forma de arco.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.012 CuNiTi ultra-flexível / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stop especial lingual mesial ao 21.',
    technicianNotes:
      'Análise de deflexão do fio calculada dentro dos limites elásticos do NiTi Copper.',
    mentorClinicalNotes: 'O Fio Mágico 0.012 proporcionará a desrotação sem risco de reabsorção.',
  },
  {
    id: 'CAS-2026-027-MWS',
    patientName: 'Danilo Moura',
    patientAge: 38,
    dentistId: 'DENT-002',
    dentistName: 'Dr. Roberto Takahashi',
    dentistCity: 'São Paulo - SP',
    dentistCro: 'CRO-SP 44102',
    protocol: 'Classe II',
    status: 'Em Análise Técnica',
    submissionDate: '26/02/2026',
    slaDeadline: '03/03/2026',
    slaHoursLeft: 62,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations: 'Classe II unilateral esquerda com mordida profunda. Perfil reto.',
    chiefComplaint: 'Assimetria anterior ao sorrir.',
    upperArchDetails: 'Correção de torque e retração assimétrica.',
    lowerArchDetails: 'Nivelamento lingual com controle de torque.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops pré-molares linguais.',
    technicianNotes: 'Geometria do fio superior em fase de refinamento.',
    mentorClinicalNotes: 'Verificar alinhamento da linha interincisiva com a face.',
  },
  {
    id: 'CAS-2026-028-MWS',
    patientName: 'Julio Cesar Peixoto',
    patientAge: 42,
    dentistId: 'DENT-004',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    dentistCro: 'CRO-MG 31209',
    protocol: 'Classe III',
    status: 'Em Análise Técnica',
    submissionDate: '27/02/2026',
    slaDeadline: '03/03/2026',
    slaHoursLeft: 66,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Classe III cirúrgica convertida para compensação dentoalveolar com fios linguais robóticos.',
    chiefComplaint: 'Quero evitar cirurgia ortognática e ter dentes funcionais.',
    upperArchDetails: 'Expansão e projeção de incisivos superiores com torque lingual positivo.',
    lowerArchDetails: 'Verticalização lingual de incisivos inferiores.',
    wireType: 'Fio Mágico TMA Lingual Customizado',
    wireGauges: 'Superior: 0.016x0.022 TMA / Inferior: 0.016x0.022 TMA',
    stopsAndAttachments: 'Ganchos linguais para elásticos de Classe III.',
    technicianNotes: 'Estudo de sobreposição cefalométrica importado no software.',
    mentorClinicalNotes: 'Mentoria direta com o Dr. Leonardo recomendada antes da liberação final.',
  },
  {
    id: 'CAS-2026-029-MWS',
    patientName: 'Roberta Linhares',
    patientAge: 33,
    dentistId: 'DENT-009',
    dentistName: 'Dra. Renata Fontes',
    dentistCity: 'Rio de Janeiro - RJ',
    dentistCro: 'CRO-RJ 22419',
    protocol: 'Classe I',
    status: 'Em Análise Técnica',
    submissionDate: '27/02/2026',
    slaDeadline: '03/03/2026',
    slaHoursLeft: 70,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Espaçamentos localizados e apinhamento ântero-inferior com perda de suporte ósseo moderada.',
    chiefComplaint: 'Dentes abrindo espaço e gengiva recuando.',
    upperArchDetails: 'Fechamento de diastemas com forças ultra-leves.',
    lowerArchDetails: 'Nivelamento lingual com diagrama passivo.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.012 CuNiTi / Inferior: 0.012 CuNiTi',
    stopsAndAttachments: 'Stops nos caninos.',
    technicianNotes: 'Cálculo de forças dissipadas para preservação do periodonto reduzido.',
    mentorClinicalNotes:
      'Forças bio-compatíveis do Fio Mágico garantem segurança clínica nesse biótipo fino.',
  },
  {
    id: 'CAS-2026-030-MWS',
    patientName: 'Vinicius Arruda',
    patientAge: 30,
    dentistId: 'DENT-010',
    dentistName: 'Dr. Marcelo Mendonça',
    dentistCity: 'Brasília - DF',
    dentistCro: 'CRO-DF 14930',
    protocol: 'Classe V',
    status: 'Em Análise Técnica',
    submissionDate: '27/02/2026',
    slaDeadline: '04/03/2026',
    slaHoursLeft: 74,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations: 'Mordida cruzada em tesoura (Brodie syndrome) no quadrante 2.',
    chiefComplaint: 'Dentes de cima mordem totalmente por fora dos dentes de baixo.',
    upperArchDetails: 'Constrição de dentes posteriores com fio palatino lingual.',
    lowerArchDetails: 'Vestibularização controlada do segmento inferior esquerdo.',
    wireType: 'Fio Mágico TMA Lingual Robótico com Torque Invertido',
    wireGauges: 'Superior: 0.016x0.022 TMA Lingual / Inferior: 0.016 CuNiTi',
    stopsAndAttachments: 'Stops molares e encaixes para tração elástica intermaxilar.',
    technicianNotes: 'Simulação das dobras robóticas de 3ª ordem no setor posterior esquerdo.',
    mentorClinicalNotes: 'Definição de passos de ativação a cada 6 semanas.',
  },

  // 14 Planejamento Elaborado
  {
    id: 'CAS-2026-031-MWS',
    patientName: 'Maria Silva',
    patientAge: 27,
    dentistId: 'DENT-004',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    dentistCro: 'CRO-MG 31209',
    protocol: 'Classe II',
    status: 'Planejamento Elaborado',
    submissionDate: '15/02/2026',
    slaDeadline: '28/02/2026',
    slaHoursLeft: 10,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Prioridade no fechamento de diastema com fios linguais customizados. Paciente modelo fotográfico.',
    chiefComplaint: 'Necessidade de invisibilidade absoluta do aparelho para fotos e desfiles.',
    upperArchDetails: 'Fechamento de diastema interincisal de 2.4mm com torque lingual de coroa.',
    lowerArchDetails: 'Alinhamento ântero-inferior sem alteração de largura intercaninos.',
    wireType: 'Fio Mágico Copper NiTi + TMA Lingual Customizado',
    wireGauges: 'Arcada Superior: 0.016 CuNiTi / Arcada Inferior: 0.014 CuNiTi',
    stopsAndAttachments:
      'Stops linguais integrados entre 11-12 e 21-22 para evitar deslizamento do fio.',
    technicianNotes:
      'Planejamento laboratorial concluído. Fio lingual superior programado com curva de retração passiva e pré-ativação de 1.2mm.',
    mentorClinicalNotes:
      'Nota do Mentor (Prof. Dr. Marcelo): Orientar a colagem indireta com o guia de silicone de alta precisão MWS. O caso responderá em menos de 5 meses.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-032-MWS',
    patientName: 'João Santos',
    patientAge: 35,
    dentistId: 'DENT-002',
    dentistName: 'Dr. Roberto Takahashi',
    dentistCity: 'São Paulo - SP',
    dentistCro: 'CRO-SP 44102',
    protocol: 'Classe I',
    status: 'Planejamento Elaborado',
    submissionDate: '20/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 22,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Ancoragem lingual com diagrama de dobras robotizadas. Apinhamento severo inferior.',
    chiefComplaint: 'Dentes da arcada inferior sobrepostos e sorriso estreito.',
    upperArchDetails: 'Expansão suave do arco para acomodação da arcada inferior desapinhada.',
    lowerArchDetails: 'Desdobramento do apinhamento anterior com Fio Mágico termoativado.',
    wireType: 'Fio Mágico Copper NiTi Lingual Robótico',
    wireGauges: 'Arcada Superior: 0.014 CuNiTi / Arcada Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops mesiais dos primeiros molares inferiores.',
    technicianNotes:
      'Diagrama de arcos robóticos gerado. Braquetes linguais com base individualizada para anatomia lingual dos incisivos.',
    mentorClinicalNotes:
      'Nota da Mentora (Dra. Helena): Manter fio 0.014 por 8 semanas antes de transição para o arco secundário.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-033-MWS',
    patientName: 'Clarice Fontoura',
    patientAge: 31,
    dentistId: 'DENT-005',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    dentistCro: 'CRO-PR 28410',
    protocol: 'Classe III',
    status: 'Planejamento Elaborado',
    submissionDate: '18/02/2026',
    slaDeadline: '27/02/2026',
    slaHoursLeft: 8,
    slaStatus: 'alerta',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations:
      'Compensação de Classe III com topo anterior. Solicita simulação 3D para apresentar ao paciente.',
    chiefComplaint: 'Dificuldade para mastigar e dentes anteriores batendo direto.',
    upperArchDetails: 'Projeção de 1.5mm com torque lingual positivo.',
    lowerArchDetails:
      'Retroinclinação dos incisivos inferiores com IPR de 0.2mm nos contatos anteriores.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Arcada Superior: 0.016 CuNiTi / Arcada Inferior: 0.016 TMA Lingual',
    stopsAndAttachments: 'Stops distais e botões linguais no 33 e 43.',
    technicianNotes: 'Simulação tridimensional anexada ao dossiê clínico digital.',
    mentorClinicalNotes:
      'Nota do Mentor (Dr. Fernando): Caso ideal para protocolo de avanço gradual superior.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-034-MWS',
    patientName: 'Bruno Castilho',
    patientAge: 29,
    dentistId: 'DENT-006',
    dentistName: 'Dr. Gustavo Siqueira',
    dentistCity: 'Campinas - SP',
    dentistCro: 'CRO-SP 52914',
    protocol: 'Classe II',
    status: 'Planejamento Elaborado',
    submissionDate: '19/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 24,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Classe II divisão 2 com mordida profunda e retroinclinação severa dos incisivos superiores.',
    chiefComplaint: 'Dentes virados para dentro parecendo menores do que são.',
    upperArchDetails: 'Torque vestibular de coroa com dobra de 3ª ordem robótica de 15 graus.',
    lowerArchDetails: 'Nivelamento da curva de Spee profunda com platôs oclusais.',
    wireType: 'Fio Mágico TMA Lingual Customizado Robótico',
    wireGauges: 'Superior: 0.016x0.022 TMA Lingual / Inferior: 0.016 CuNiTi',
    stopsAndAttachments: 'Levantes de mordida linguais em resina nos dentes 11 e 21.',
    technicianNotes: 'Aparelho lingual MWS com braquetes de perfil baixo no setor anterior.',
    mentorClinicalNotes:
      'Nota do Mentor (Prof. Dr. Marcelo): Fundamental a cimentação dos platôs linguais para desocluir os molares e permitir nivelamento inferior.',
    dentistFeedbackStatus: 'ajustes_solicitados',
    dentistFeedbackNotes:
      'Solicitou revisão da espessura do platô lingual no dente 11 para não incomodar na mastigação.',
  },
  {
    id: 'CAS-2026-035-MWS',
    patientName: 'Elisa Bittencourt',
    patientAge: 42,
    dentistId: 'DENT-007',
    dentistName: 'Dra. Fernanda Albuquerque',
    dentistCity: 'Porto Alegre - RS',
    dentistCro: 'CRO-RS 19821',
    protocol: 'Classe I',
    status: 'Planejamento Elaborado',
    submissionDate: '19/02/2026',
    slaDeadline: '01/03/2026',
    slaHoursLeft: 26,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations: 'Alinhamento para reabilitação cerâmica dos incisivos superiores.',
    chiefComplaint: 'Quero alinhar antes de colocar facetas de porcelana.',
    upperArchDetails: 'Distribuição dos diastemas para proporção áurea dental.',
    lowerArchDetails: 'Sem tratamento necessário.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Arcada Superior: 0.014 CuNiTi / Inferior: Sem aparelho',
    stopsAndAttachments: 'Stops no 14 e 24.',
    technicianNotes:
      'Distribuição milimétrica de espaços calculada em conjunto com o enceramento de diagnóstico.',
    mentorClinicalNotes:
      'Nota da Mentora (Dra. Helena): Excelente colaboração inter-especialidades. Caso rápido estimado em 4 meses.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-036-MWS',
    patientName: 'Fabio Junqueira',
    patientAge: 38,
    dentistId: 'DENT-008',
    dentistName: 'Dr. Bruno Silveira',
    dentistCity: 'Ribeirão Preto - SP',
    dentistCro: 'CRO-SP 38921',
    protocol: 'Classe IV',
    status: 'Planejamento Elaborado',
    submissionDate: '20/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 36,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations:
      'Mordida aberta anterior de 2.5mm decorrente de respiração bucal crônica.',
    chiefComplaint: 'Dentes anteriores abertos.',
    upperArchDetails: 'Intrusão molar leve e extrusão incisal relativa com dobras de 2ª ordem.',
    lowerArchDetails: 'Achatamento da curva de Spee reversa.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Arcada Superior: 0.016 CuNiTi / Arcada Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops caninos linguais.',
    technicianNotes: 'Trajetória robótica do fio calculada com curva acentuada no arco superior.',
    mentorClinicalNotes:
      'Nota do Mentor (Dr. Fernando): Cuidado com a fonação nas primeiras duas semanas; fonética normaliza no dia 10.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-037-MWS',
    patientName: 'Natalia Dornelles',
    patientAge: 24,
    dentistId: 'DENT-002',
    dentistName: 'Dr. Roberto Takahashi',
    dentistCity: 'São Paulo - SP',
    dentistCro: 'CRO-SP 44102',
    protocol: 'Classe II',
    status: 'Planejamento Elaborado',
    submissionDate: '21/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 38,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations: 'Classe II divisão 1 moderada em jovem adulta. Linha de sorriso alta.',
    chiefComplaint: 'Dentes de cima projetados e insegurança para sorrir.',
    upperArchDetails: 'Retração lingual de 3mm com controle biomecânico de centro de resistência.',
    lowerArchDetails: 'Nivelamento passivo lingual.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Arcada Superior: 0.016x0.022 CuNiTi / Arcada Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops mesiais e ganchos linguais soldados para tração leve.',
    technicianNotes:
      'Fio Mágico de arco contínuo lingual robótico sem perda de controle de torque.',
    mentorClinicalNotes:
      'Nota do Mentor (Prof. Dr. Marcelo): Seguir sequência recomendada no guia técnico MWS.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-038-MWS',
    patientName: 'Rogerio Macedo',
    patientAge: 46,
    dentistId: 'DENT-009',
    dentistName: 'Dra. Renata Fontes',
    dentistCity: 'Rio de Janeiro - RJ',
    dentistCro: 'CRO-RJ 22419',
    protocol: 'Classe I',
    status: 'Planejamento Elaborado',
    submissionDate: '21/02/2026',
    slaDeadline: '02/03/2026',
    slaHoursLeft: 40,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Apinhamento ântero-inferior com apinhamento leve superior em executivo de finanças.',
    chiefComplaint: 'Necessita de aparelho imperceptível por razões corporativas.',
    upperArchDetails: 'Conformação de arco em U com expansão posterior de 1mm.',
    lowerArchDetails: 'Alinhamento ântero-inferior com Fio Mágico 0.014 CuNiTi.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops caninos linguais.',
    technicianNotes: 'Setup virtual aprovado internamente pelo time técnico.',
    mentorClinicalNotes:
      'Nota da Mentora (Dra. Helena): Caso clássico MWS, ideal para previsibilidade de curto prazo.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-039-MWS',
    patientName: 'Monique Silveira',
    patientAge: 33,
    dentistId: 'DENT-010',
    dentistName: 'Dr. Marcelo Mendonça',
    dentistCity: 'Brasília - DF',
    dentistCro: 'CRO-DF 14930',
    protocol: 'Classe V',
    status: 'Planejamento Elaborado',
    submissionDate: '21/02/2026',
    slaDeadline: '03/03/2026',
    slaHoursLeft: 48,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations:
      'Mordida cruzada unilateral posterior no dente 16 e 17 com inclinação lingual.',
    chiefComplaint: 'Dentes posteriores cruzados com impacto na mastigação.',
    upperArchDetails: 'Expansão robótica setorial superior direita.',
    lowerArchDetails: 'Arco estabilizado.',
    wireType: 'Fio Mágico TMA Lingual Customizado com Braço de Expansão',
    wireGauges: 'Superior: 0.016x0.022 TMA Lingual / Inferior: Sem aparelho ativo',
    stopsAndAttachments: 'Stops no 15 e botões linguais.',
    technicianNotes:
      'Dobra de 1ª ordem de expansão de 3.2mm calibrada para a arcada superior direita.',
    mentorClinicalNotes:
      'Nota do Mentor (Dr. Fernando): Cimentação com guia indireto de três secções facilitará a inserção.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-040-MWS',
    patientName: 'Renan Castro',
    patientAge: 28,
    dentistId: 'DENT-004',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    dentistCro: 'CRO-MG 31209',
    protocol: 'Classe II',
    status: 'Planejamento Elaborado',
    submissionDate: '22/02/2026',
    slaDeadline: '03/03/2026',
    slaHoursLeft: 52,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Sobressaliência moderada com apinhamento ântero-inferior em paciente com hábito atlético.',
    chiefComplaint: 'Pratico esportes de contato e não posso usar braquetes pela frente.',
    upperArchDetails: 'Retração com controle de torque.',
    lowerArchDetails: 'Nivelamento e alinhamento lingual sem vestibularização.',
    wireType: 'Fio Mágico Copper NiTi Lingual Robótico',
    wireGauges: 'Arcada Superior: 0.016 CuNiTi / Arcada Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops nos molares linguais.',
    technicianNotes:
      'Posicionamento lingual protege lábios e bochechas contra impactos esportivos.',
    mentorClinicalNotes:
      'Nota do Mentor (Prof. Dr. Marcelo): Excelente caso para a indicação lingual esportiva.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-041-MWS',
    patientName: 'Debora Antunes',
    patientAge: 36,
    dentistId: 'DENT-005',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    dentistCro: 'CRO-PR 28410',
    protocol: 'Classe I',
    status: 'Planejamento Elaborado',
    submissionDate: '22/02/2026',
    slaDeadline: '04/03/2026',
    slaHoursLeft: 60,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Giroversões bilaterais de pré-molares superiores e apinhamento incisal inferior.',
    chiefComplaint: 'Dentes virados do lado e dentes de baixo encavalados.',
    upperArchDetails: 'Desrotação de pré-molares com torque passivo.',
    lowerArchDetails: 'Desdobramento do apinhamento anterior.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops no 14 e 24.',
    technicianNotes: 'Ângulos de inserção lingual calculados com extrema fidelidade anatômica.',
    mentorClinicalNotes:
      'Nota da Mentora (Dra. Helena): Seguir com colagem indireta completa em sessão única.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-042-MWS',
    patientName: 'Alexandre Prado',
    patientAge: 40,
    dentistId: 'DENT-006',
    dentistName: 'Dr. Gustavo Siqueira',
    dentistCity: 'Campinas - SP',
    dentistCro: 'CRO-SP 52914',
    protocol: 'Classe III',
    status: 'Planejamento Elaborado',
    submissionDate: '22/02/2026',
    slaDeadline: '04/03/2026',
    slaHoursLeft: 62,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations: 'Classe III leve com mordida de topo anterior em paciente adulto.',
    chiefComplaint: 'Quero descruzar a mordida sem cirurgia.',
    upperArchDetails: 'Avanço incisal lingual com torque radicular palatino de 10 graus.',
    lowerArchDetails: 'Recuo lingual suave dos 4 incisivos inferiores.',
    wireType: 'Fio Mágico TMA Lingual Customizado Robótico',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.016 TMA Lingual',
    stopsAndAttachments: 'Stops molares.',
    technicianNotes: 'Dossiê técnico finalizado e pronto para download do ortodontista.',
    mentorClinicalNotes:
      'Nota do Mentor (Dr. Fernando): Planejamento validado, pronto para aprovação clínica do Dr. Gustavo.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-043-MWS',
    patientName: 'Isabela Fontes',
    patientAge: 25,
    dentistId: 'DENT-007',
    dentistName: 'Dra. Fernanda Albuquerque',
    dentistCity: 'Porto Alegre - RS',
    dentistCro: 'CRO-RS 19821',
    protocol: 'Classe I',
    status: 'Planejamento Elaborado',
    submissionDate: '23/02/2026',
    slaDeadline: '04/03/2026',
    slaHoursLeft: 68,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Diastema interincisal superior de 1.8mm e apinhamento discreto inferior.',
    chiefComplaint: 'Fechar o espaço entre os dois dentes da frente.',
    upperArchDetails: 'Fechamento com forças contínuas leves de 35 gramas.',
    lowerArchDetails: 'Nivelamento passivo lingual.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.012 CuNiTi',
    stopsAndAttachments: 'Stops linguais bilaterais.',
    technicianNotes: 'Configuração dos fios linguais otimizada para mínima retenção de placa.',
    mentorClinicalNotes:
      'Nota da Mentora (Dra. Helena): Caso rápido e de alta satisfação imediata.',
    dentistFeedbackStatus: 'pendente',
  },
  {
    id: 'CAS-2026-044-MWS',
    patientName: 'Marcela Vianna',
    patientAge: 32,
    dentistId: 'DENT-008',
    dentistName: 'Dr. Bruno Silveira',
    dentistCity: 'Ribeirão Preto - SP',
    dentistCro: 'CRO-SP 38921',
    protocol: 'Classe II',
    status: 'Planejamento Elaborado',
    submissionDate: '23/02/2026',
    slaDeadline: '05/03/2026',
    slaHoursLeft: 76,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations: 'Classe II unilateral direita de 2mm com curva de Spee acentuada.',
    chiefComplaint: 'Dentes tortos do lado direito e sorriso caído.',
    upperArchDetails: 'Mecânica unilateral lingual com dobra robotizada de compensação.',
    lowerArchDetails: 'Nivelamento lingual com platôs de desoclusão.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops no 16 e platôs nos centrais.',
    technicianNotes: 'Planejamento e notas elaboradas. Aguardando aceite do Dr. Bruno.',
    mentorClinicalNotes:
      'Nota do Mentor (Prof. Dr. Marcelo): Estarei à disposição via chat para acompanhar a primeira consulta de ativação.',
    dentistFeedbackStatus: 'pendente',
  },

  // 10 Planejamento Entregue (Ortodontista aprovou e liberou para produção dos fios)
  {
    id: 'CAS-2026-045-MWS',
    patientName: 'Ana Costa',
    patientAge: 30,
    dentistId: 'DENT-005',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    dentistCro: 'CRO-PR 28410',
    protocol: 'Classe III',
    status: 'Planejamento Entregue',
    submissionDate: '08/02/2026',
    slaDeadline: '24/02/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Compensação esquelética lingual com fios especiais de níquel-titânio termoativado robótico.',
    chiefComplaint: 'Mordida invertida e desejo de aparelho invisível.',
    upperArchDetails: 'Expansão robótica e torque radicular lingual.',
    lowerArchDetails: 'Retroinclinação e ancoragem lingual passiva.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado Robótico',
    wireGauges: 'Arcada Superior: 0.016 CuNiTi / Arcada Inferior: 0.016 TMA Lingual',
    stopsAndAttachments: 'Stops no 16, 26, 36, 46 com encaixes linguais.',
    technicianNotes:
      'Planejamento entregue e aprovado pela Dra. Vanessa. Arquivos robóticos G-Code enviados para a Célula KUKA-MW-01.',
    mentorClinicalNotes:
      'Nota do Mentor (Prof. Dr. Marcelo Carvalho): Caso liberado para produção robótica. Dra. Vanessa aprovou o plano sem ressalvas em 24/02.',
    dentistFeedbackStatus: 'aprovado',
    dentistFeedbackNotes:
      'Planejamento impecável. Aprovado para fabricação imediata dos fios linguais.',
    feedbackDate: '24/02/2026',
    productionStage: 'acabamento',
    productionBatchId: 'BAT-2026-089',
    roboticCellId: 'KUKA-MW-01',
  },
  {
    id: 'CAS-2026-046-MWS',
    patientName: 'Lucas Ferreira',
    patientAge: 33,
    dentistId: 'DENT-004',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    dentistCro: 'CRO-MG 31209',
    protocol: 'Classe II',
    status: 'Planejamento Entregue',
    submissionDate: '10/01/2026',
    slaDeadline: '25/01/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Planejamento entregue. Aparelho lingual instalado com sucesso na clínica do licenciado.',
    chiefComplaint: 'Apinhamento e retrognatismo mandibular suave.',
    upperArchDetails: 'Retração em massa anterior com controle de torque.',
    lowerArchDetails: 'Nivelamento lingual completo.',
    wireType: 'Fio Mágico TMA Lingual Robótico Customizado',
    wireGauges: 'Arcada Superior: 0.016x0.022 TMA Lingual / Inferior: 0.016 CuNiTi',
    stopsAndAttachments: 'Stops linguais bilaterais.',
    technicianNotes: 'Fios Mágicos produzidos, conferidos pelo CQ e entregues.',
    mentorClinicalNotes:
      'Nota do Mentor (Prof. Dr. Marcelo Carvalho): Acompanhando evolução clínica com o Dr. Leonardo. Paciente adaptado.',
    dentistFeedbackStatus: 'aprovado',
    feedbackDate: '26/01/2026',
    productionStage: 'pronto_expedicao',
    productionBatchId: 'BAT-2026-044',
    roboticCellId: 'KUKA-MW-02',
  },
  {
    id: 'CAS-2026-047-MWS',
    patientName: 'Fernanda Lins',
    patientAge: 28,
    dentistId: 'DENT-002',
    dentistName: 'Dr. Roberto Takahashi',
    dentistCity: 'São Paulo - SP',
    dentistCro: 'CRO-SP 44102',
    protocol: 'Classe I',
    status: 'Planejamento Entregue',
    submissionDate: '12/02/2026',
    slaDeadline: '25/02/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Fechamento de espaços bidentais anteriores com alinhamento estético de alta precisão.',
    chiefComplaint: 'Aparelho 100% invisível por trás dos dentes.',
    upperArchDetails: 'Fechamento em massa com fio Copper NiTi robótico.',
    lowerArchDetails: 'Manutenção de estabilidade intercaninos.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops nos primeiros molares.',
    technicianNotes: 'Produção robótica em andamento na bancada de controle de qualidade.',
    mentorClinicalNotes:
      'Nota da Mentora (Dra. Helena Barreto): Plano aprovado pelo Dr. Roberto em 25/02.',
    dentistFeedbackStatus: 'aprovado',
    feedbackDate: '25/02/2026',
    productionStage: 'controle_qualidade',
    productionBatchId: 'BAT-2026-092',
    roboticCellId: 'KUKA-MW-01',
  },
  {
    id: 'CAS-2026-048-MWS',
    patientName: 'Rodrigo Medeiros',
    patientAge: 41,
    dentistId: 'DENT-006',
    dentistName: 'Dr. Gustavo Siqueira',
    dentistCity: 'Campinas - SP',
    dentistCro: 'CRO-SP 52914',
    protocol: 'Classe II',
    status: 'Planejamento Entregue',
    submissionDate: '14/02/2026',
    slaDeadline: '26/02/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations: 'Classe II divisão 2 com curva de Spee profunda e mordida travada.',
    chiefComplaint: 'Dentes superiores tampam os inferiores e machucam o palato.',
    upperArchDetails: 'Torque de coroa lingual e desoclusão com platôs em compósito.',
    lowerArchDetails: 'Extrusão de pré-molares inferiores e nivelamento de Spee.',
    wireType: 'Fio Mágico TMA Lingual Robótico',
    wireGauges: 'Superior: 0.016x0.022 TMA Lingual / Inferior: 0.016 CuNiTi',
    stopsAndAttachments: 'Platôs linguais nos incisivos centrais e laterais.',
    technicianNotes:
      'Fios dobrados pela célula robótica. Enviados para a etapa de polimento e controle de qualidade.',
    mentorClinicalNotes:
      'Nota do Mentor (Dr. Fernando Prado): O Dr. Gustavo confirmou colagem agendada para semana que vem.',
    dentistFeedbackStatus: 'aprovado',
    feedbackDate: '26/02/2026',
    productionStage: 'dobagem_modelagem',
    productionBatchId: 'BAT-2026-095',
    roboticCellId: 'KUKA-MW-02',
  },
  {
    id: 'CAS-2026-049-MWS',
    patientName: 'Mariana Guimarães',
    patientAge: 29,
    dentistId: 'DENT-007',
    dentistName: 'Dra. Fernanda Albuquerque',
    dentistCity: 'Porto Alegre - RS',
    dentistCro: 'CRO-RS 19821',
    protocol: 'Classe I',
    status: 'Planejamento Entregue',
    submissionDate: '15/02/2026',
    slaDeadline: '26/02/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Apinhamento leve superior e moderado inferior em profissional de relações públicas.',
    chiefComplaint: 'Necessidade de tecnologia invisível sem aparelhos plásticos removíveis.',
    upperArchDetails: 'Alinhamento com Fio Mágico 0.014 CuNiTi termoativado.',
    lowerArchDetails: 'Desdobramento do apinhamento com dobras robóticas individualizadas.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops no 34 e 44.',
    technicianNotes: 'Lote de fios finalizado no controle de qualidade; pronto para expedição.',
    mentorClinicalNotes:
      'Nota da Mentora (Dra. Helena Barreto): Caso com excelente adaptação esperada.',
    dentistFeedbackStatus: 'aprovado',
    feedbackDate: '26/02/2026',
    productionStage: 'pronto_expedicao',
    productionBatchId: 'BAT-2026-096',
    roboticCellId: 'KUKA-MW-01',
  },
  {
    id: 'CAS-2026-050-MWS',
    patientName: 'Carlos Eduardo Prado',
    patientAge: 36,
    dentistId: 'DENT-008',
    dentistName: 'Dr. Bruno Silveira',
    dentistCity: 'Ribeirão Preto - SP',
    dentistCro: 'CRO-SP 38921',
    protocol: 'Classe IV',
    status: 'Planejamento Entregue',
    submissionDate: '16/02/2026',
    slaDeadline: '27/02/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations: 'Mordida aberta anterior com interposição lingual.',
    chiefComplaint: 'Dentes anteriores não se tocam.',
    upperArchDetails: 'Extrusão anterior e nivelamento do plano oclusal.',
    lowerArchDetails: 'Achatamento da curva de Spee reversa.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.016 CuNiTi',
    stopsAndAttachments: 'Levantes de mordida posteriores.',
    technicianNotes: 'Fios produzidos pela célula robótica KUKA-MW-02.',
    mentorClinicalNotes: 'Nota do Mentor (Dr. Fernando Prado): Plano aceito e aprovado.',
    dentistFeedbackStatus: 'aprovado',
    feedbackDate: '27/02/2026',
    productionStage: 'acabamento',
    productionBatchId: 'BAT-2026-098',
    roboticCellId: 'KUKA-MW-02',
  },
  {
    id: 'CAS-2026-051-MWS',
    patientName: 'Carolina Silveira',
    patientAge: 26,
    dentistId: 'DENT-009',
    dentistName: 'Dra. Renata Fontes',
    dentistCity: 'Rio de Janeiro - RJ',
    dentistCro: 'CRO-RJ 22419',
    protocol: 'Classe I',
    status: 'Planejamento Entregue',
    submissionDate: '17/02/2026',
    slaDeadline: '27/02/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dra. Helena Barreto',
    clinicalObservations:
      'Giroversões moderadas nos incisivos centrais superiores e caninos inferiores.',
    chiefComplaint: 'Dentes tortos aparentes ao sorrir.',
    upperArchDetails: 'Desrotação pura com o Fio Mágico 0.014 CuNiTi lingual.',
    lowerArchDetails: 'Alinhamento suave lingual.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.014 CuNiTi / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops nos molares.',
    technicianNotes: 'Célula robótica finalizou a conformação dos fios superior e inferior.',
    mentorClinicalNotes:
      'Nota da Mentora (Dra. Helena Barreto): Aprovado pela Dra. Renata em 27/02.',
    dentistFeedbackStatus: 'aprovado',
    feedbackDate: '27/02/2026',
    productionStage: 'controle_qualidade',
    productionBatchId: 'BAT-2026-101',
    roboticCellId: 'KUKA-MW-01',
  },
  {
    id: 'CAS-2026-052-MWS',
    patientName: 'Vinicius Fagundes',
    patientAge: 39,
    dentistId: 'DENT-010',
    dentistName: 'Dr. Marcelo Mendonça',
    dentistCity: 'Brasília - DF',
    dentistCro: 'CRO-DF 14930',
    protocol: 'Classe II',
    status: 'Planejamento Entregue',
    submissionDate: '17/02/2026',
    slaDeadline: '28/02/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Lucas Rocha (Técnico Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations: 'Classe II divisão 1 com sobremordida acentuada e diastemas posteriores.',
    chiefComplaint: 'Dentes para frente e queixo retraído.',
    upperArchDetails: 'Retração em bloco com Fio Mágico lingual retangular.',
    lowerArchDetails: 'Nivelamento e intrusão anterior suave.',
    wireType: 'Fio Mágico TMA Lingual Robótico',
    wireGauges: 'Superior: 0.016x0.022 TMA Lingual / Inferior: 0.016 CuNiTi',
    stopsAndAttachments: 'Stops mesiais e ganchos linguais soldados.',
    technicianNotes: 'Modelagem robótica dos fios em execução na Célula 02.',
    mentorClinicalNotes:
      'Nota do Mentor (Prof. Dr. Marcelo Carvalho): Aprovado pelo Dr. Marcelo Mendonça.',
    dentistFeedbackStatus: 'aprovado',
    feedbackDate: '27/02/2026',
    productionStage: 'dobagem_modelagem',
    productionBatchId: 'BAT-2026-103',
    roboticCellId: 'KUKA-MW-02',
  },
  {
    id: 'CAS-2026-053-MWS',
    patientName: 'Vanessa Alcantara',
    patientAge: 31,
    dentistId: 'DENT-004',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    dentistCro: 'CRO-MG 31209',
    protocol: 'Classe III',
    status: 'Planejamento Entregue',
    submissionDate: '18/02/2026',
    slaDeadline: '28/02/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Camila Morais (Técnica Lab)',
    mentorAssigned: 'Prof. Dr. Marcelo Carvalho',
    clinicalObservations:
      'Classe III esquelética moderada com compensação dentária com Fio Mágico.',
    chiefComplaint: 'Mordida invertida e insatisfação com tratamentos convencionais.',
    upperArchDetails: 'Expansão e avanço incisal.',
    lowerArchDetails: 'Retroinclinação e ancoragem lingual.',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    wireGauges: 'Superior: 0.016 CuNiTi / Inferior: 0.016 TMA Lingual',
    stopsAndAttachments: 'Stops no 16 e 26.',
    technicianNotes: 'Fios finalizados e aprovados pelo controle de qualidade.',
    mentorClinicalNotes: 'Nota do Mentor (Prof. Dr. Marcelo Carvalho): Caso liberado para envio.',
    dentistFeedbackStatus: 'aprovado',
    feedbackDate: '28/02/2026',
    productionStage: 'pronto_expedicao',
    productionBatchId: 'BAT-2026-104',
    roboticCellId: 'KUKA-MW-01',
  },
  {
    id: 'CAS-2026-054-MWS',
    patientName: 'Guilherme Peçanha',
    patientAge: 35,
    dentistId: 'DENT-005',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    dentistCro: 'CRO-PR 28410',
    protocol: 'Classe V',
    status: 'Planejamento Entregue',
    submissionDate: '18/02/2026',
    slaDeadline: '28/02/2026',
    slaHoursLeft: 0,
    slaStatus: 'normal',
    technicianAssigned: 'Gabriel Pires (Técnico Robótica)',
    mentorAssigned: 'Dr. Fernando Prado',
    clinicalObservations: 'Mordida cruzada unilateral e apinhamento superior.',
    chiefComplaint: 'Mastigação estalando e dentes posteriores desencontrados.',
    upperArchDetails: 'Expansão diferencial com fio lingual customizado.',
    lowerArchDetails: 'Alinhamento lingual passivo.',
    wireType: 'Fio Mágico TMA Lingual Customizado com Braços Robóticos',
    wireGauges: 'Superior: 0.016x0.022 TMA Lingual / Inferior: 0.014 CuNiTi',
    stopsAndAttachments: 'Stops molares bilaterais.',
    technicianNotes: 'Fios concluídos na célula robótica KUKA-MW-01 e validados pelo CQ.',
    mentorClinicalNotes:
      'Nota do Mentor (Dr. Fernando Prado): Planejamento entregue e validado com louvor.',
    dentistFeedbackStatus: 'aprovado',
    feedbackDate: '28/02/2026',
    productionStage: 'pronto_expedicao',
    productionBatchId: 'BAT-2026-105',
    roboticCellId: 'KUKA-MW-01',
  },
]

// Equipe Técnica do Laboratório MWS
export const MOCK_LAB_TEAM: LabTeamMember[] = [
  {
    id: 'TECH-01',
    name: 'Prof. Dr. Marcelo Carvalho',
    role: 'Planejador & Mentor',
    avatarSeed: 101,
    email: 'marcelo.carvalho@magicwire.com.br',
    casesAssignedCount: 18,
    capacity: 25,
    specialty: 'Biomecânica Lingual Avançada & Casos Cirúrgicos Complexos (Classe II e III)',
    status: 'ativo',
    completedThisMonth: 22,
    npsScore: 9.9,
  },
  {
    id: 'TECH-02',
    name: 'Dra. Helena Barreto',
    role: 'Planejador & Mentor',
    avatarSeed: 102,
    email: 'helena.barreto@magicwire.com.br',
    casesAssignedCount: 14,
    capacity: 20,
    specialty: 'Ortodontia Lingual Adulta, Apinhamentos Severos & Estética do Sorriso',
    status: 'ativo',
    completedThisMonth: 19,
    npsScore: 9.8,
  },
  {
    id: 'TECH-03',
    name: 'Dr. Fernando Prado',
    role: 'Planejador & Mentor',
    avatarSeed: 103,
    email: 'fernando.prado@magicwire.com.br',
    casesAssignedCount: 11,
    capacity: 20,
    specialty: 'Mecânica Lingual de 3ª Geração, Mordidas Abertas & Cruzadas (Classe IV e V)',
    status: 'ativo',
    completedThisMonth: 16,
    npsScore: 9.7,
  },
  {
    id: 'TECH-04',
    name: 'Lucas Rocha',
    role: 'Técnico Especialista',
    avatarSeed: 104,
    email: 'lucas.rocha@magicwire.com.br',
    casesAssignedCount: 15,
    capacity: 20,
    specialty: 'Setup 3D Lingual, Segmentação Digital & Modelagem de Arcos MWS',
    status: 'ativo',
    completedThisMonth: 28,
    npsScore: 9.6,
  },
  {
    id: 'TECH-05',
    name: 'Camila Morais',
    role: 'Técnica Especialista',
    avatarSeed: 105,
    email: 'camila.morais@magicwire.com.br',
    casesAssignedCount: 13,
    capacity: 18,
    specialty: 'Colagem Indireta Guiada Lingual, Platôs e Levantes Oclusais em Resina',
    status: 'ativo',
    completedThisMonth: 25,
    npsScore: 9.8,
  },
  {
    id: 'TECH-06',
    name: 'Gabriel Pires',
    role: 'Especialista em Robótica',
    avatarSeed: 106,
    email: 'gabriel.pires@magicwire.com.br',
    casesAssignedCount: 10,
    capacity: 15,
    specialty: 'Calibração das Células Robóticas KUKA-MW, Dobragem de NiTi Copper e TMA',
    status: 'ativo',
    completedThisMonth: 34,
    npsScore: 9.9,
  },
  {
    id: 'TECH-07',
    name: 'Engª Juliana Sato',
    role: 'Coordenador Técnico',
    avatarSeed: 107,
    email: 'juliana.sato@magicwire.com.br',
    casesAssignedCount: 4,
    capacity: 10,
    specialty: 'Gestão da Qualidade ISO 13485, Controle Dimensional de Fios & SLAs da Esteira',
    status: 'ativo',
    completedThisMonth: 12,
    npsScore: 10.0,
  },
]

// Fila de Fabricação Robótica (casos aprovados)
export const MOCK_ROBOTIC_ORDERS: RoboticProductionOrder[] = [
  {
    id: 'ROB-2026-089',
    caseId: 'CAS-2026-045-MWS',
    patientName: 'Ana Costa',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    protocol: 'Classe III',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado Robótico',
    upperWireGauge: '0.016 CuNiTi Lingual',
    lowerWireGauge: '0.016 TMA Lingual',
    stage: 'acabamento',
    priority: 'urgente',
    roboticCell: 'Célula Robótica KUKA-MW-01',
    startedAt: '25/02/2026 09:30',
    estimatedCompletion: '27/02/2026 14:00',
    qualityCheckPassed: false,
    technicianInCharge: 'Gabriel Pires',
  },
  {
    id: 'ROB-2026-092',
    caseId: 'CAS-2026-047-MWS',
    patientName: 'Fernanda Lins',
    dentistName: 'Dr. Roberto Takahashi',
    dentistCity: 'São Paulo - SP',
    protocol: 'Classe I',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    upperWireGauge: '0.014 CuNiTi Lingual',
    lowerWireGauge: '0.014 CuNiTi Lingual',
    stage: 'controle_qualidade',
    priority: 'alta',
    roboticCell: 'Célula Robótica KUKA-MW-01',
    startedAt: '25/02/2026 14:15',
    estimatedCompletion: '27/02/2026 18:00',
    qualityCheckPassed: true,
    technicianInCharge: 'Engª Juliana Sato',
  },
  {
    id: 'ROB-2026-095',
    caseId: 'CAS-2026-048-MWS',
    patientName: 'Rodrigo Medeiros',
    dentistName: 'Dr. Gustavo Siqueira',
    dentistCity: 'Campinas - SP',
    protocol: 'Classe II',
    wireType: 'Fio Mágico TMA Lingual Robótico',
    upperWireGauge: '0.016x0.022 TMA Lingual',
    lowerWireGauge: '0.016 CuNiTi Lingual',
    stage: 'dobagem_modelagem',
    priority: 'normal',
    roboticCell: 'Célula Robótica KUKA-MW-02',
    startedAt: '26/02/2026 11:00',
    estimatedCompletion: '28/02/2026 16:30',
    qualityCheckPassed: false,
    technicianInCharge: 'Gabriel Pires',
  },
  {
    id: 'ROB-2026-096',
    caseId: 'CAS-2026-049-MWS',
    patientName: 'Mariana Guimarães',
    dentistName: 'Dra. Fernanda Albuquerque',
    dentistCity: 'Porto Alegre - RS',
    protocol: 'Classe I',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    upperWireGauge: '0.014 CuNiTi Lingual',
    lowerWireGauge: '0.014 CuNiTi Lingual',
    stage: 'pronto_expedicao',
    priority: 'normal',
    roboticCell: 'Célula Robótica KUKA-MW-01',
    startedAt: '24/02/2026 16:00',
    estimatedCompletion: '26/02/2026 17:00',
    qualityCheckPassed: true,
    technicianInCharge: 'Lucas Rocha',
  },
  {
    id: 'ROB-2026-098',
    caseId: 'CAS-2026-050-MWS',
    patientName: 'Carlos Eduardo Prado',
    dentistName: 'Dr. Bruno Silveira',
    dentistCity: 'Ribeirão Preto - SP',
    protocol: 'Classe IV',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    upperWireGauge: '0.016 CuNiTi Lingual',
    lowerWireGauge: '0.016 CuNiTi Lingual',
    stage: 'acabamento',
    priority: 'normal',
    roboticCell: 'Célula Robótica KUKA-MW-02',
    startedAt: '26/02/2026 08:30',
    estimatedCompletion: '28/02/2026 12:00',
    qualityCheckPassed: false,
    technicianInCharge: 'Gabriel Pires',
  },
  {
    id: 'ROB-2026-101',
    caseId: 'CAS-2026-051-MWS',
    patientName: 'Carolina Silveira',
    dentistName: 'Dra. Renata Fontes',
    dentistCity: 'Rio de Janeiro - RJ',
    protocol: 'Classe I',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    upperWireGauge: '0.014 CuNiTi Lingual',
    lowerWireGauge: '0.014 CuNiTi Lingual',
    stage: 'controle_qualidade',
    priority: 'alta',
    roboticCell: 'Célula Robótica KUKA-MW-01',
    startedAt: '26/02/2026 13:45',
    estimatedCompletion: '28/02/2026 15:00',
    qualityCheckPassed: true,
    technicianInCharge: 'Engª Juliana Sato',
  },
  {
    id: 'ROB-2026-103',
    caseId: 'CAS-2026-052-MWS',
    patientName: 'Vinicius Fagundes',
    dentistName: 'Dr. Marcelo Mendonça',
    dentistCity: 'Brasília - DF',
    protocol: 'Classe II',
    wireType: 'Fio Mágico TMA Lingual Robótico',
    upperWireGauge: '0.016x0.022 TMA Lingual',
    lowerWireGauge: '0.016 CuNiTi Lingual',
    stage: 'dobagem_modelagem',
    priority: 'normal',
    roboticCell: 'Célula Robótica KUKA-MW-02',
    startedAt: '27/02/2026 08:00',
    estimatedCompletion: '01/03/2026 14:00',
    qualityCheckPassed: false,
    technicianInCharge: 'Gabriel Pires',
  },
  {
    id: 'ROB-2026-104',
    caseId: 'CAS-2026-053-MWS',
    patientName: 'Vanessa Alcantara',
    dentistName: 'Dr. Leonardo Duarte',
    dentistCity: 'Belo Horizonte - MG',
    protocol: 'Classe III',
    wireType: 'Fio Mágico Copper NiTi Lingual Customizado',
    upperWireGauge: '0.016 CuNiTi Lingual',
    lowerWireGauge: '0.016 TMA Lingual',
    stage: 'pronto_expedicao',
    priority: 'alta',
    roboticCell: 'Célula Robótica KUKA-MW-01',
    startedAt: '25/02/2026 10:00',
    estimatedCompletion: '27/02/2026 11:30',
    qualityCheckPassed: true,
    technicianInCharge: 'Lucas Rocha',
  },
  {
    id: 'ROB-2026-105',
    caseId: 'CAS-2026-054-MWS',
    patientName: 'Guilherme Peçanha',
    dentistName: 'Dra. Vanessa Meirelles',
    dentistCity: 'Curitiba - PR',
    protocol: 'Classe V',
    wireType: 'Fio Mágico TMA Lingual Customizado com Braços Robóticos',
    upperWireGauge: '0.016x0.022 TMA Lingual',
    lowerWireGauge: '0.014 CuNiTi Lingual',
    stage: 'pronto_expedicao',
    priority: 'urgente',
    roboticCell: 'Célula Robótica KUKA-MW-01',
    startedAt: '25/02/2026 14:00',
    estimatedCompletion: '27/02/2026 17:00',
    qualityCheckPassed: true,
    technicianInCharge: 'Engª Juliana Sato',
  },
]

// SLAs por Etapa Oficial
export const MOCK_LAB_SLAS: LabSlaMetric[] = [
  {
    stage: 'Aguardando Análise Técnica',
    averageTimeHours: 14.2,
    targetHours: 24.0,
    onTimePercentage: 91.7, // 1 caso estourado em 12
    delayedCasesCount: 1,
  },
  {
    stage: 'Em Análise Técnica',
    averageTimeHours: 32.8,
    targetHours: 48.0,
    onTimePercentage: 94.4, // 1 caso estourado em 18
    delayedCasesCount: 1,
  },
  {
    stage: 'Planejamento Elaborado',
    averageTimeHours: 28.5,
    targetHours: 48.0,
    onTimePercentage: 100.0,
    delayedCasesCount: 0,
  },
  {
    stage: 'Planejamento Entregue',
    averageTimeHours: 18.2,
    targetHours: 24.0,
    onTimePercentage: 100.0,
    delayedCasesCount: 0,
  },
]

// Histórico de Produtividade Semanal (Análises e Planejamentos Concluídos)
export const MOCK_LAB_WEEKLY_PRODUCTIVITY = [
  { day: 'Seg', analises: 8, planejamentos: 6, producaoFios: 7 },
  { day: 'Ter', analises: 11, planejamentos: 9, producaoFios: 10 },
  { day: 'Qua', analises: 14, planejamentos: 12, producaoFios: 12 },
  { day: 'Qui', analises: 16, planejamentos: 11, producaoFios: 13 },
  { day: 'Sex', analises: 13, planejamentos: 10, producaoFios: 11 },
  { day: 'Sáb', analises: 5, planejamentos: 4, producaoFios: 6 },
]

export const MOCK_LAB_SETTINGS = {
  labName: 'Laboratório Central MWS - Unidade Robótica Tecnológica',
  cnpj: '38.921.841/0001-92',
  responsibleOfficer: 'Engª Juliana Sato / Prof. Dr. Marcelo Carvalho',
  address: 'Av. Paulista, 1842 - Torre Norte, 14º Andar - São Paulo, SP',
  contactEmail: 'lab@magicwire.com',
  contactPhone: '(11) 3288-9000',
  dailyWireCapacity: 45, // fios robóticos por dia
  roboticCellsCount: 3,
  activeTechnicians: 7,
  emailNotificationsOnNewCase: true,
  emailNotificationsOnFeedback: true,
  smsAlertOnSlaBreach: true,
  autoAssignMentorByProtocol: true,
  defaultWireMaterial: 'Copper NiTi Lingual 3ª Geração',
}
